model:
  name: 'resnet50_fc512'
  pretrained: True

data:
  type: 'image'
  source: 'config_dataset'
  coco_dir: 'bottlenose_dolphin'
  height: 384
  width: 384
  transforms_train: ['resize', 'random_affine', 'color_jitter', 'random_grayscale']
  transforms_test: ['resize']
  version: 'v1'
  use_viewpoint: False
  split_test: 'val2021'
  train_min_samples: 3
  test_min_samples: 2

loss:
  name: 'triplet'
  triplet:
    weight_t: 1.
    weight_x: 1.
  softmax:
    label_smooth: True

sampler:
  num_instances: 4
  num_copies: 4

train:
  optim: 'adam'
  lr: 0.00001
  max_epoch: 200
  batch_size: 32
  fixbase_epoch: 1
  open_layers: ['fc', 'classifier']
  lr_scheduler: 'multi_step'
  stepsize: [110]

test:
  batch_size: 100
  dist_metric: 'euclidean'
  normalize_feature: False
  evaluate: False
  eval_freq: 10
  rerank: False
  ranks: [1, 5, 12, 20]
  visrank_topk: 5
  visrank_resize: False
  # Flip image if a model have been trained on one specific view (animal_wbia.py)
  # fliplr: True
  # fliplr_view: ['left']


